<?php
$pageTitle = "Noticia";
include_once("app/view/default/includes/header.php");
?>

<div class = "news">
	<div class = "newsText">
		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla egestas ex nisl, eu accumsan sapien condimentum in. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam viverra accumsan ligula. Suspendisse non commodo felis, porta facilisis massa. Curabitur ullamcorper felis non quam egestas ullamcorper. Aliquam erat volutpat. Sed malesuada, nunc ac lobortis finibus, lectus massa malesuada turpis, quis lacinia neque lacus vel velit. Nam posuere mauris et eleifend egestas. Etiam mattis eu eros at volutpat. Duis sapien libero, lobortis sit amet tempor non, gravida et erat. Ut ut urna quis nibh mollis auctor at id diam. Aliquam erat volutpat. Curabitur feugiat in velit eget tempor. Cras velit enim, cursus ut laoreet sollicitudin, commodo nec arcu. Nullam accumsan felis neque, vel pretium velit varius sed. Suspendisse dapibus posuere neque, sit amet auctor metus placerat eu.

		Nam at porta urna, vitae iaculis dui. Nam ipsum nibh, elementum ut cursus at, facilisis in arcu. Cras bibendum lorem laoreet varius pretium. Vestibulum et dictum sapien. Integer accumsan magna sit amet dapibus egestas. Nullam non mauris sit amet lectus vehicula euismod. Nullam accumsan luctus ultricies. Sed sodales, dolor in ullamcorper consectetur, orci nibh sagittis felis, ac vestibulum risus quam ac metus. Pellentesque aliquam ligula eget magna rhoncus, vitae consequat leo pharetra. Nulla dapibus tempor quam, rhoncus lobortis lacus hendrerit ultricies. Donec et libero viverra, imperdiet justo eget, bibendum magna. Quisque et facilisis justo. Sed porttitor malesuada nunc at egestas. Integer sapien velit, mollis sit amet nunc malesuada, maximus fringilla urna. Cras id rhoncus magna, sit amet blandit nibh.

		Mauris odio eros, vestibulum quis pretium nec, tincidunt ut augue. Integer at magna nisi. In tempor condimentum lorem ultrices hendrerit. Donec nisi ex, lobortis vitae metus ut, molestie egestas purus. Vestibulum nec lobortis orci. Proin tempor, magna sed fermentum dignissim, metus metus accumsan augue, vel elementum velit mauris in lectus. Cras eros magna, egestas in aliquam quis, consectetur at est. Aliquam diam ipsum, posuere vitae risus at, elementum ultricies turpis. Nullam mollis massa ac diam finibus, in iaculis elit porta. Maecenas volutpat ut augue eget sollicitudin. Sed ultrices suscipit molestie. Morbi in libero pretium, lobortis orci at, lobortis nibh. Fusce porta nibh ac dolor porttitor aliquam. Nullam ac lorem elit. Fusce sit amet vehicula quam. Donec nibh nibh, pellentesque non fringilla id, dapibus nec ligula.

		Quisque ac consequat lectus. Aliquam at commodo dui, ac imperdiet libero. Donec tincidunt accumsan nisi. Nulla euismod leo vitae pharetra convallis. Fusce efficitur libero urna, in molestie augue accumsan sit amet. Mauris turpis arcu, scelerisque non ornare eget, aliquam nec arcu. Suspendisse potenti. Curabitur tincidunt, nulla vitae ullamcorper congue, felis augue sagittis eros, pellentesque efficitur ex neque mattis sem. Aliquam feugiat rhoncus leo id ornare. Praesent ac convallis urna. Maecenas posuere euismod dictum. Phasellus sem elit, faucibus ultrices cursus in, vulputate non nisi. Integer consectetur accumsan mauris, nec dictum ante aliquam et. Proin pharetra pulvinar justo non malesuada.

		Nullam ac nibh vel nibh consectetur venenatis a quis sem. Aliquam egestas massa dui, et blandit ipsum pharetra sed. Sed blandit quam sem, in bibendum est viverra eu. Mauris eget risus ut nulla efficitur mollis eu a est. Aliquam eget venenatis ante. Sed finibus, nisl eu porta iaculis, nibh mi varius lorem, non fringilla ex est eget magna. Quisque et bibendum ligula. Nunc aliquam efficitur elit vel ullamcorper. Aliquam sit amet ultricies enim, congue placerat nisi. Fusce arcu magna, iaculis ut tincidunt vitae, scelerisque eget metus. Fusce finibus dictum felis, in vulputate lorem suscipit non. Etiam dictum, odio non elementum sagittis, urna nibh blandit odio, quis imperdiet est velit id arcu.
		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla egestas ex nisl, eu accumsan sapien condimentum in. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam viverra accumsan ligula. Suspendisse non commodo felis, porta facilisis massa. Curabitur ullamcorper felis non quam egestas ullamcorper. Aliquam erat volutpat. Sed malesuada, nunc ac lobortis finibus, lectus massa malesuada turpis, quis lacinia neque lacus vel velit. Nam posuere mauris et eleifend egestas. Etiam mattis eu eros at volutpat. Duis sapien libero, lobortis sit amet tempor non, gravida et erat. Ut ut urna quis nibh mollis auctor at id diam. Aliquam erat volutpat. Curabitur feugiat in velit eget tempor. Cras velit enim, cursus ut laoreet sollicitudin, commodo nec arcu. Nullam accumsan felis neque, vel pretium velit varius sed. Suspendisse dapibus posuere neque, sit amet auctor metus placerat eu.

		Nam at porta urna, vitae iaculis dui. Nam ipsum nibh, elementum ut cursus at, facilisis in arcu. Cras bibendum lorem laoreet varius pretium. Vestibulum et dictum sapien. Integer accumsan magna sit amet dapibus egestas. Nullam non mauris sit amet lectus vehicula euismod. Nullam accumsan luctus ultricies. Sed sodales, dolor in ullamcorper consectetur, orci nibh sagittis felis, ac vestibulum risus quam ac metus. Pellentesque aliquam ligula eget magna rhoncus, vitae consequat leo pharetra. Nulla dapibus tempor quam, rhoncus lobortis lacus hendrerit ultricies. Donec et libero viverra, imperdiet justo eget, bibendum magna. Quisque et facilisis justo. Sed porttitor malesuada nunc at egestas. Integer sapien velit, mollis sit amet nunc malesuada, maximus fringilla urna. Cras id rhoncus magna, sit amet blandit nibh.

		Mauris odio eros, vestibulum quis pretium nec, tincidunt ut augue. Integer at magna nisi. In tempor condimentum lorem ultrices hendrerit. Donec nisi ex, lobortis vitae metus ut, molestie egestas purus. Vestibulum nec lobortis orci. Proin tempor, magna sed fermentum dignissim, metus metus accumsan augue, vel elementum velit mauris in lectus. Cras eros magna, egestas in aliquam quis, consectetur at est. Aliquam diam ipsum, posuere vitae risus at, elementum ultricies turpis. Nullam mollis massa ac diam finibus, in iaculis elit porta. Maecenas volutpat ut augue eget sollicitudin. Sed ultrices suscipit molestie. Morbi in libero pretium, lobortis orci at, lobortis nibh. Fusce porta nibh ac dolor porttitor aliquam. Nullam ac lorem elit. Fusce sit amet vehicula quam. Donec nibh nibh, pellentesque non fringilla id, dapibus nec ligula.

		Quisque ac consequat lectus. Aliquam at commodo dui, ac imperdiet libero. Donec tincidunt accumsan nisi. Nulla euismod leo vitae pharetra convallis. Fusce efficitur libero urna, in molestie augue accumsan sit amet. Mauris turpis arcu, scelerisque non ornare eget, aliquam nec arcu. Suspendisse potenti. Curabitur tincidunt, nulla vitae ullamcorper congue, felis augue sagittis eros, pellentesque efficitur ex neque mattis sem. Aliquam feugiat rhoncus leo id ornare. Praesent ac convallis urna. Maecenas posuere euismod dictum. Phasellus sem elit, faucibus ultrices cursus in, vulputate non nisi. Integer consectetur accumsan mauris, nec dictum ante aliquam et. Proin pharetra pulvinar justo non malesuada.

		Nullam ac nibh vel nibh consectetur venenatis a quis sem. Aliquam egestas massa dui, et blandit ipsum pharetra sed. Sed blandit quam sem, in bibendum est viverra eu. Mauris eget risus ut nulla efficitur mollis eu a est. Aliquam eget venenatis ante. Sed finibus, nisl eu porta iaculis, nibh mi varius lorem, non fringilla ex est eget magna. Quisque et bibendum ligula. Nunc aliquam efficitur elit vel ullamcorper. Aliquam sit amet ultricies enim, congue placerat nisi. Fusce arcu magna, iaculis ut tincidunt vitae, scelerisque eget metus. Fusce finibus dictum felis, in vulputate lorem suscipit non. Etiam dictum, odio non elementum sagittis, urna nibh blandit odio, quis imperdiet est velit id arcu.
		<div class = "navButtons">
				<button id = "readMore">Seguir leyendo</button>
		</div>
	</div>

	<div class = "storyNav">
		<div class = "authorInfo">Pepitillo666</div>
		<div>Añadir a Favoritos</div>
		<div class = "floatOptions">
			<button class = "storyOptions">Poner marcador en este capítulo</button>

		</div>
	</div>
</div>

<?php
include_once("app/view/default/includes/footer.php");
?>